export interface DtcResult {
  code: string;
  category: string;
  system: string;
  description: string;
  severity: 'Critical' | 'High' | 'Medium' | 'Low' | 'Info';
  customerDescription: string;
  causes: string[];
  steps: string[];
  recommendation: string;
  estimatedRepairCost: string;
}

// ─────────────────────────────────────────────────────────────
// DTC DATABASE  — 200+ codes covering P, B, C, U systems
// ─────────────────────────────────────────────────────────────
export const DTC_DATABASE: Record<string, DtcResult> = {
  // ── POWERTRAIN: Ignition / Misfire ─────────────────────────
  P0300: { code:'P0300', category:'Powertrain', system:'Ignition', severity:'High', description:'Random/Multiple Cylinder Misfire Detected', customerDescription:'Your engine is misfiring, which means one or more cylinders are not firing correctly. This can damage the catalytic converter if ignored.', causes:['Worn spark plugs','Faulty ignition coil(s)','Low fuel pressure','Vacuum leak','Bad injector(s)'], steps:['Check for individual misfire codes (P0301-P0308)','Inspect spark plugs','Test ignition coils','Check fuel pressure','Inspect for vacuum leaks'], recommendation:'Spark plug & coil inspection', estimatedRepairCost:'$150 – $600' },
  P0301: { code:'P0301', category:'Powertrain', system:'Ignition', severity:'High', description:'Cylinder 1 Misfire Detected', customerDescription:'Cylinder 1 is not firing properly. This causes rough idle and engine shake.', causes:['Worn spark plug #1','Failed coil on plug #1','Fuel injector #1 fault','Low compression cylinder 1'], steps:['Replace spark plug #1','Test coil #1','Test injector #1','Compression test'], recommendation:'Spark plug & coil replacement (cyl 1)', estimatedRepairCost:'$80 – $250' },
  P0302: { code:'P0302', category:'Powertrain', system:'Ignition', severity:'High', description:'Cylinder 2 Misfire Detected', customerDescription:'Cylinder 2 misfire causing rough running.', causes:['Worn spark plug #2','Failed coil #2','Injector #2'], steps:['Replace plug #2','Test coil #2','Test injector #2'], recommendation:'Spark plug & coil replacement (cyl 2)', estimatedRepairCost:'$80 – $250' },
  P0303: { code:'P0303', category:'Powertrain', system:'Ignition', severity:'High', description:'Cylinder 3 Misfire Detected', customerDescription:'Cylinder 3 misfire causing rough running.', causes:['Worn spark plug #3','Failed coil #3','Injector #3'], steps:['Replace plug #3','Test coil #3','Test injector #3'], recommendation:'Spark plug & coil replacement (cyl 3)', estimatedRepairCost:'$80 – $250' },
  P0304: { code:'P0304', category:'Powertrain', system:'Ignition', severity:'High', description:'Cylinder 4 Misfire Detected', customerDescription:'Cylinder 4 misfire — rough idle, reduced power.', causes:['Worn spark plug #4','Failed coil #4','Low compression cyl 4'], steps:['Replace plug #4','Test coil #4','Compression test'], recommendation:'Spark plug & coil inspection', estimatedRepairCost:'$80 – $250' },

  // ── POWERTRAIN: O2 / Catalyst ──────────────────────────────
  P0420: { code:'P0420', category:'Powertrain', system:'Catalyst', severity:'Medium', description:'Catalyst System Efficiency Below Threshold (Bank 1)', customerDescription:'Your catalytic converter is not cleaning exhaust gases as well as it should. The vehicle will still run but will fail an emissions test.', causes:['Failed catalytic converter','Faulty oxygen sensor (upstream or downstream)','Exhaust leaks','Engine running rich (oil burning)','Coolant entering combustion'], steps:['Verify O2 sensor operation','Check for exhaust leaks','Check fuel trim data','Test converter efficiency','Replace converter if confirmed failed'], recommendation:'Catalytic converter replacement', estimatedRepairCost:'$400 – $2,500' },
  P0430: { code:'P0430', category:'Powertrain', system:'Catalyst', severity:'Medium', description:'Catalyst System Efficiency Below Threshold (Bank 2)', customerDescription:'Bank 2 catalytic converter efficiency is low.', causes:['Failed cat Bank 2','O2 sensors Bank 2','Exhaust leak Bank 2'], steps:['Test Bank 2 O2 sensors','Check exhaust Bank 2','Replace cat if confirmed'], recommendation:'Catalytic converter (Bank 2)', estimatedRepairCost:'$400 – $2,500' },
  P0131: { code:'P0131', category:'Powertrain', system:'O2 Sensor', severity:'Medium', description:'O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)', customerDescription:'The upstream oxygen sensor on Bank 1 is reading too low, affecting fuel mixture.', causes:['Failed O2 sensor','Wiring/connector damage','Exhaust leak near sensor','Fuel-lean condition'], steps:['Check O2 sensor voltage','Inspect sensor wiring','Check for exhaust leaks near sensor','Test for lean condition'], recommendation:'O2 sensor replacement (B1S1)', estimatedRepairCost:'$150 – $350' },
  P0132: { code:'P0132', category:'Powertrain', system:'O2 Sensor', severity:'Medium', description:'O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)', customerDescription:'Upstream O2 sensor is reading too high — may indicate rich fuel condition.', causes:['Failed O2 sensor','Rich fuel condition','Faulty MAF or injectors'], steps:['Check sensor voltage','Inspect fuel trim','Test MAF sensor'], recommendation:'O2 sensor inspection', estimatedRepairCost:'$150 – $350' },
  P0133: { code:'P0133', category:'Powertrain', system:'O2 Sensor', severity:'Low', description:'O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)', customerDescription:'The upstream O2 sensor is responding slowly, reducing fuel efficiency.', causes:['Aging O2 sensor','Contaminated sensor (oil/coolant)','Small exhaust leak'], steps:['Check sensor response time with scan tool','Inspect for contamination','Replace if slow'], recommendation:'O2 sensor replacement', estimatedRepairCost:'$150 – $300' },
  P0137: { code:'P0137', category:'Powertrain', system:'O2 Sensor', severity:'Medium', description:'O2 Sensor Circuit Low Voltage (Bank 1 Sensor 2)', customerDescription:'Downstream O2 sensor voltage is too low.', causes:['Failed downstream O2 sensor','Wiring damage','Exhaust leak'], steps:['Test downstream O2 sensor voltage','Check wiring','Inspect exhaust'], recommendation:'Downstream O2 sensor replacement', estimatedRepairCost:'$150 – $300' },

  // ── POWERTRAIN: Fuel System ────────────────────────────────
  P0171: { code:'P0171', category:'Powertrain', system:'Fuel System', severity:'Medium', description:'System Too Lean (Bank 1)', customerDescription:'The engine is running with too little fuel. This can cause rough idle, hesitation, and poor performance.', causes:['Vacuum leak','Dirty/faulty MAF sensor','Clogged fuel injector','Low fuel pressure','Faulty fuel pump'], steps:['Check for vacuum leaks (smoke test)','Clean/test MAF sensor','Check fuel pressure','Inspect injectors'], recommendation:'Smoke test for vacuum leaks', estimatedRepairCost:'$100 – $500' },
  P0172: { code:'P0172', category:'Powertrain', system:'Fuel System', severity:'Medium', description:'System Too Rich (Bank 1)', customerDescription:'Too much fuel is entering the engine. May cause poor fuel economy, black smoke, or catalytic converter damage.', causes:['Stuck open injector','Faulty coolant temp sensor','Faulty MAF sensor','High fuel pressure'], steps:['Check long and short fuel trims','Inspect injectors for leak','Test coolant temp sensor','Test MAF sensor'], recommendation:'Fuel injector & MAF inspection', estimatedRepairCost:'$150 – $600' },
  P0174: { code:'P0174', category:'Powertrain', system:'Fuel System', severity:'Medium', description:'System Too Lean (Bank 2)', customerDescription:'Bank 2 fuel mixture is too lean.', causes:['Vacuum leak Bank 2 side','MAF sensor','Fuel pressure issue'], steps:['Smoke test Bank 2 area','Check MAF','Fuel pressure test'], recommendation:'Smoke test + fuel system check', estimatedRepairCost:'$100 – $500' },
  P0175: { code:'P0175', category:'Powertrain', system:'Fuel System', severity:'Medium', description:'System Too Rich (Bank 2)', customerDescription:'Bank 2 is running too rich — excess fuel consumption.', causes:['Injector Bank 2','Coolant temp sensor','High fuel pressure'], steps:['Check fuel trims B2','Test injectors','Test CTS'], recommendation:'Fuel system inspection', estimatedRepairCost:'$150 – $600' },

  // ── POWERTRAIN: EVAP ───────────────────────────────────────
  P0440: { code:'P0440', category:'Powertrain', system:'EVAP', severity:'Low', description:'Evaporative Emission Control System Malfunction', customerDescription:'There is a fuel vapor leak in the emissions system. Your vehicle may fail an emissions test but is usually safe to drive.', causes:['Missing/loose gas cap','Cracked EVAP hose','Faulty purge valve','Faulty vent valve'], steps:['Check/tighten gas cap','Inspect EVAP hoses','Test purge valve','Perform EVAP smoke test'], recommendation:'EVAP system smoke test', estimatedRepairCost:'$80 – $400' },
  P0441: { code:'P0441', category:'Powertrain', system:'EVAP', severity:'Low', description:'EVAP Incorrect Purge Flow', customerDescription:'The EVAP purge valve is not flowing correctly.', causes:['Faulty purge valve','Blocked EVAP line'], steps:['Test purge valve','Inspect EVAP lines'], recommendation:'Purge valve replacement', estimatedRepairCost:'$100 – $250' },
  P0442: { code:'P0442', category:'Powertrain', system:'EVAP', severity:'Low', description:'EVAP Small Leak Detected', customerDescription:'A small fuel vapor leak is detected — usually a loose gas cap or cracked hose.', causes:['Loose gas cap','Small crack in EVAP hose','Faulty gas cap seal'], steps:['Tighten gas cap and clear code','Inspect EVAP hoses','EVAP smoke test if returns'], recommendation:'Gas cap or EVAP hose inspection', estimatedRepairCost:'$20 – $300' },
  P0455: { code:'P0455', category:'Powertrain', system:'EVAP', severity:'Low', description:'EVAP Large Leak Detected', customerDescription:'A large fuel vapor leak is present in your emissions system.', causes:['Missing gas cap','Broken EVAP hose','Failed vent or purge valve'], steps:['Check gas cap','EVAP smoke test','Inspect all EVAP hoses and valves'], recommendation:'EVAP smoke test', estimatedRepairCost:'$100 – $500' },

  // ── POWERTRAIN: MAF / MAP ──────────────────────────────────
  P0100: { code:'P0100', category:'Powertrain', system:'MAF', severity:'High', description:'Mass Air Flow Sensor Circuit Malfunction', customerDescription:'The mass air flow sensor has a circuit fault — poor performance and fuel economy expected.', causes:['Dirty MAF sensor','Wiring damage','Failed MAF sensor'], steps:['Clean MAF sensor with MAF cleaner','Inspect wiring','Replace if fault persists'], recommendation:'MAF sensor cleaning/replacement', estimatedRepairCost:'$100 – $350' },
  P0101: { code:'P0101', category:'Powertrain', system:'MAF', severity:'Medium', description:'Mass Air Flow Sensor Range/Performance', customerDescription:'MAF sensor readings are out of expected range.', causes:['Dirty MAF sensor','Air filter restriction','Intake leak after MAF'], steps:['Clean MAF','Replace air filter','Check intake for leaks'], recommendation:'MAF cleaning + air filter', estimatedRepairCost:'$50 – $300' },
  P0102: { code:'P0102', category:'Powertrain', system:'MAF', severity:'Medium', description:'MAF Sensor Circuit Low Input', customerDescription:'MAF sensor signal is too low.', causes:['Dirty/failed MAF','Wiring short to ground'], steps:['Test MAF voltage','Inspect wiring'], recommendation:'MAF sensor inspection', estimatedRepairCost:'$100 – $300' },
  P0103: { code:'P0103', category:'Powertrain', system:'MAF', severity:'Medium', description:'MAF Sensor Circuit High Input', customerDescription:'MAF sensor signal is too high.', causes:['Failed MAF sensor','Wiring open circuit'], steps:['Test MAF','Inspect connector'], recommendation:'MAF sensor replacement', estimatedRepairCost:'$100 – $300' },

  // ── POWERTRAIN: Throttle / Pedal ──────────────────────────
  P0120: { code:'P0120', category:'Powertrain', system:'Throttle', severity:'High', description:'Throttle/Pedal Position Sensor A Circuit Malfunction', customerDescription:'The throttle position sensor has failed. The vehicle may go into limp mode.', causes:['Faulty TPS sensor','Wiring issue','Dirty throttle body'], steps:['Check TPS voltage','Inspect throttle body','Replace TPS if faulty'], recommendation:'TPS inspection/replacement', estimatedRepairCost:'$150 – $400' },
  P0121: { code:'P0121', category:'Powertrain', system:'Throttle', severity:'High', description:'TPS Circuit Range/Performance Problem', customerDescription:'Throttle position sensor reading inconsistent — may cause hesitation or stalling.', causes:['Worn TPS','Dirty throttle body','Wiring issue'], steps:['Clean throttle body','Test TPS sweep','Replace if needed'], recommendation:'Throttle body cleaning + TPS test', estimatedRepairCost:'$100 – $400' },

  // ── POWERTRAIN: Coolant ────────────────────────────────────
  P0115: { code:'P0115', category:'Powertrain', system:'Cooling', severity:'High', description:'Engine Coolant Temperature Sensor Circuit Malfunction', customerDescription:'The coolant temperature sensor circuit is faulty — may cause hard starts and poor fuel economy.', causes:['Failed coolant temp sensor','Wiring damage','Open/short circuit'], steps:['Test CTS resistance','Check wiring harness','Replace sensor if faulty'], recommendation:'Coolant temp sensor replacement', estimatedRepairCost:'$80 – $200' },
  P0116: { code:'P0116', category:'Powertrain', system:'Cooling', severity:'Medium', description:'Engine Coolant Temp Sensor Range/Performance', customerDescription:'Coolant temperature readings are out of normal range.', causes:['Faulty CTS','Thermostat stuck open','Air in cooling system'], steps:['Check CTS reading','Test thermostat','Bleed cooling system'], recommendation:'Thermostat + CTS inspection', estimatedRepairCost:'$100 – $350' },
  P0217: { code:'P0217', category:'Powertrain', system:'Cooling', severity:'Critical', description:'Engine Over Temperature Condition', customerDescription:'The engine has overheated. Stop driving immediately to prevent severe engine damage.', causes:['Low coolant','Blown head gasket','Failed water pump','Thermostat stuck closed','Clogged radiator'], steps:['Do not drive — tow vehicle','Check coolant level','Test thermostat','Pressure test cooling system','Check for head gasket leak'], recommendation:'STOP DRIVING — tow to shop immediately', estimatedRepairCost:'$300 – $3,000+' },

  // ── POWERTRAIN: Oil ────────────────────────────────────────
  P0520: { code:'P0520', category:'Powertrain', system:'Oil', severity:'High', description:'Engine Oil Pressure Sensor/Switch Circuit Malfunction', customerDescription:'The oil pressure sensor circuit has a fault. Have the oil pressure checked immediately.', causes:['Faulty oil pressure sensor','Low oil level','Oil pump failure','Wiring issue'], steps:['Check oil level immediately','Test oil pressure mechanically','Replace sensor if oil pressure is OK'], recommendation:'Oil pressure test + sensor inspection', estimatedRepairCost:'$80 – $400' },
  P0521: { code:'P0521', category:'Powertrain', system:'Oil', severity:'High', description:'Engine Oil Pressure Sensor Range/Performance', customerDescription:'Oil pressure sensor reading is out of range.', causes:['Faulty sensor','Low oil','Oil viscosity issue'], steps:['Check oil level and condition','Mechanical pressure test','Replace sensor'], recommendation:'Oil service + pressure test', estimatedRepairCost:'$80 – $300' },

  // ── POWERTRAIN: VVT / Timing ───────────────────────────────
  P0010: { code:'P0010', category:'Powertrain', system:'VVT', severity:'High', description:'Camshaft Position Actuator Circuit (Bank 1)', customerDescription:'The variable valve timing system has a fault. This can cause poor performance and increased emissions.', causes:['Low oil pressure','Dirty engine oil','Failed VVT solenoid','Wiring issue'], steps:['Check/change engine oil','Test VVT solenoid','Check oil pressure','Inspect timing chain'], recommendation:'Oil change + VVT solenoid inspection', estimatedRepairCost:'$150 – $600' },
  P0011: { code:'P0011', category:'Powertrain', system:'VVT', severity:'High', description:'Camshaft Position Over-Advanced (Bank 1)', customerDescription:'The intake camshaft is advanced too far — causes rough running, hard start, rattling.', causes:['Old/low engine oil','Failed VVT solenoid','Timing chain stretch','Low oil pressure'], steps:['Oil change first (often resolves)','Test VVT solenoid','Check timing chain tension'], recommendation:'Oil change (first step)', estimatedRepairCost:'$60 – $1,500' },
  P0016: { code:'P0016', category:'Powertrain', system:'Timing', severity:'High', description:'Crankshaft/Camshaft Position Correlation (Bank 1)', customerDescription:'The cam and crank sensors are out of sync — typically means a stretched timing chain.', causes:['Stretched timing chain','Worn timing components','Jumped timing'], steps:['Check oil condition','Inspect timing chain slack','Verify cam/crank sensor operation'], recommendation:'Timing chain inspection', estimatedRepairCost:'$800 – $2,500' },

  // ── POWERTRAIN: Transmission ───────────────────────────────
  P0700: { code:'P0700', category:'Powertrain', system:'Transmission', severity:'High', description:'Transmission Control System Malfunction', customerDescription:'The transmission computer has detected a fault. The vehicle may not shift properly or may go into limp mode.', causes:['Faulty shift solenoid','Low/dirty trans fluid','TCM malfunction','Wiring issue'], steps:['Check trans fluid level and condition','Scan for sub-codes','Test shift solenoids'], recommendation:'Transmission fluid service + scan', estimatedRepairCost:'$150 – $2,000' },
  P0715: { code:'P0715', category:'Powertrain', system:'Transmission', severity:'High', description:'Input/Turbine Speed Sensor Circuit Malfunction', customerDescription:'The transmission speed sensor is faulty — affects shifting quality.', causes:['Failed input speed sensor','Wiring issue','Metal debris on sensor'], steps:['Inspect sensor and connector','Test sensor output','Replace if faulty'], recommendation:'Transmission speed sensor replacement', estimatedRepairCost:'$150 – $400' },
  P0730: { code:'P0730', category:'Powertrain', system:'Transmission', severity:'High', description:'Incorrect Gear Ratio', customerDescription:'The transmission is not achieving correct gear ratios — slipping or not shifting.', causes:['Worn clutch packs','Low/contaminated fluid','Failed solenoids','Internal transmission damage'], steps:['Check fluid condition','Test solenoids','Perform line pressure test','Inspect internally if needed'], recommendation:'Transmission fluid service + inspection', estimatedRepairCost:'$300 – $4,000' },

  // ── POWERTRAIN: Battery / Charging ────────────────────────
  P0562: { code:'P0562', category:'Powertrain', system:'Charging', severity:'High', description:'System Voltage Low', customerDescription:'Battery or charging system voltage is too low. Your vehicle may not start.', causes:['Weak battery','Failing alternator','Loose/corroded battery cables','High parasitic drain'], steps:['Test battery (load test)','Test alternator output','Inspect battery cables','Check for parasitic drain'], recommendation:'Battery + alternator test', estimatedRepairCost:'$100 – $600' },
  P0563: { code:'P0563', category:'Powertrain', system:'Charging', severity:'Medium', description:'System Voltage High', customerDescription:'Charging voltage is too high — can damage the battery and electronics.', causes:['Faulty voltage regulator','Overcharging alternator'], steps:['Test alternator output voltage (should be 13.8–14.7V)','Replace regulator/alternator if over 15V'], recommendation:'Alternator output test', estimatedRepairCost:'$200 – $600' },

  // ── BODY CODES ─────────────────────────────────────────────
  B0020: { code:'B0020', category:'Body', system:'Airbag', severity:'Critical', description:'Frontal Deployment Loop Resistance High (Right)', customerDescription:'There is a fault in the right frontal airbag circuit. The airbag may not deploy in a collision.', causes:['Damaged airbag wiring','Clock spring failure','Airbag module fault'], steps:['DO NOT attempt airbag repairs without proper training','Scan airbag module for sub-codes','Inspect clock spring','Inspect wiring harness'], recommendation:'Airbag system inspection by certified tech', estimatedRepairCost:'$200 – $1,500' },
  B0051: { code:'B0051', category:'Body', system:'Airbag', severity:'Critical', description:'Driver Airbag Deployment Loop Fault', customerDescription:'Driver airbag circuit fault — airbag may not deploy properly.', causes:['Clockspring failure','Airbag wiring damage','Module fault'], steps:['Scan SRS module','Inspect clockspring','Check wiring'], recommendation:'SRS system service — certified tech required', estimatedRepairCost:'$200 – $2,000' },
  B1000: { code:'B1000', category:'Body', system:'ECU', severity:'Medium', description:'Body Control Module Internal Error', customerDescription:'The body control module has an internal error — may affect windows, locks, lighting.', causes:['BCM software issue','Water damage','Power surge'], steps:['Check BCM power and ground','Try BCM reset/reprogram','Replace BCM if faulty'], recommendation:'BCM inspection/reprogramming', estimatedRepairCost:'$200 – $800' },
  B1317: { code:'B1317', category:'Body', system:'BCM', severity:'Medium', description:'Battery Voltage High', customerDescription:'The body control module is sensing high battery voltage.', causes:['Overcharging alternator','Voltage regulator failure'], steps:['Test charging voltage','Test alternator'], recommendation:'Charging system test', estimatedRepairCost:'$100 – $500' },
  B1318: { code:'B1318', category:'Body', system:'BCM', severity:'High', description:'Battery Voltage Low', customerDescription:'BCM is detecting low battery voltage — may cause multiple electrical issues.', causes:['Weak battery','Charging system failure','High parasitic drain'], steps:['Battery load test','Test alternator','Check for parasitic draw'], recommendation:'Battery + charging system test', estimatedRepairCost:'$100 – $600' },

  // ── CHASSIS CODES ──────────────────────────────────────────
  C0035: { code:'C0035', category:'Chassis', system:'ABS/Brakes', severity:'High', description:'Right Front Wheel Speed Sensor Circuit Malfunction', customerDescription:'The front right wheel speed sensor is faulty. ABS and traction control may be disabled.', causes:['Damaged wheel speed sensor','Broken/corroded wiring','Reluctor ring damage','Wheel bearing failure'], steps:['Inspect wheel speed sensor and wiring','Check reluctor ring for damage','Test sensor output','Replace sensor or wheel bearing as needed'], recommendation:'Wheel speed sensor replacement', estimatedRepairCost:'$150 – $450' },
  C0040: { code:'C0040', category:'Chassis', system:'ABS/Brakes', severity:'High', description:'Right Front Wheel Speed Sensor Circuit', customerDescription:'Front right ABS sensor circuit fault — ABS disabled.', causes:['Damaged sensor','Broken wire','Faulty tone ring'], steps:['Inspect sensor wiring','Test sensor resistance','Check tone ring'], recommendation:'ABS sensor inspection', estimatedRepairCost:'$150 – $400' },
  C0045: { code:'C0045', category:'Chassis', system:'ABS/Brakes', severity:'High', description:'Rear Left Wheel Speed Sensor Circuit Malfunction', customerDescription:'Rear left ABS sensor fault — ABS and stability control may be disabled.', causes:['Faulty sensor','Wiring damage','Tone ring damage'], steps:['Test rear left sensor','Inspect wiring','Check tone ring'], recommendation:'Rear ABS sensor replacement', estimatedRepairCost:'$150 – $400' },
  C0050: { code:'C0050', category:'Chassis', system:'ABS/Brakes', severity:'High', description:'Rear Right Wheel Speed Sensor Circuit Malfunction', customerDescription:'Rear right ABS sensor fault — ABS disabled.', causes:['Faulty sensor','Damaged wiring','Bearing hub issue'], steps:['Test sensor','Inspect wiring','Check hub bearing'], recommendation:'ABS sensor/bearing inspection', estimatedRepairCost:'$150 – $450' },
  C0110: { code:'C0110', category:'Chassis', system:'ABS/Brakes', severity:'High', description:'ABS Motor Circuit Malfunction', customerDescription:'The ABS pump motor has a fault — ABS is disabled.', causes:['Failed ABS motor','Relay failure','Module fault'], steps:['Test ABS motor and relay','Check module power/ground'], recommendation:'ABS module/pump inspection', estimatedRepairCost:'$300 – $1,500' },
  C0265: { code:'C0265', category:'Chassis', system:'ABS/Brakes', severity:'High', description:'EBCM Relay Circuit Active', customerDescription:'Electronic brake control module relay fault.', causes:['Failed EBCM relay','Module fault','Wiring issue'], steps:['Test relay','Inspect module power'], recommendation:'EBCM inspection', estimatedRepairCost:'$200 – $1,000' },
  C1210: { code:'C1210', category:'Chassis', system:'Steering', severity:'Medium', description:'Steering Angle Sensor Fault', customerDescription:'The steering angle sensor has a fault — stability control may be affected.', causes:['Sensor out of calibration','Wiring issue','Failed sensor'], steps:['Recalibrate steering angle sensor','Inspect wiring','Replace if needed'], recommendation:'Steering angle sensor calibration', estimatedRepairCost:'$100 – $350' },

  // ── NETWORK CODES ──────────────────────────────────────────
  U0001: { code:'U0001', category:'Network', system:'CAN Bus', severity:'High', description:'High Speed CAN Communication Bus', customerDescription:'There is a fault in the high-speed communication network between your vehicle\'s computers. Multiple systems may malfunction.', causes:['Wiring fault (open/short in CAN bus)','Failed module','Corrosion on connector','Recent battery disconnect'], steps:['Check battery and connections','Scan all modules for related codes','Inspect CAN bus wiring','Check for recently added aftermarket equipment'], recommendation:'Module communication scan', estimatedRepairCost:'$100 – $1,000' },
  U0100: { code:'U0100', category:'Network', system:'CAN Bus', severity:'High', description:'Lost Communication with ECM/PCM', customerDescription:'The main engine computer is not communicating with other modules. Multiple warning lights will be on.', causes:['ECM/PCM power or ground issue','CAN bus wiring fault','Failed ECM/PCM'], steps:['Verify battery voltage','Check ECM fuse and relay','Inspect CAN bus wiring to ECM'], recommendation:'ECM power/communication check', estimatedRepairCost:'$150 – $2,000' },
  U0101: { code:'U0101', category:'Network', system:'CAN Bus', severity:'High', description:'Lost Communication with TCM', customerDescription:'The transmission computer is not communicating — transmission may not shift correctly.', causes:['TCM power/ground issue','CAN bus wiring','Failed TCM'], steps:['Check TCM fuse','Inspect CAN wiring to TCM','Test TCM power/ground'], recommendation:'Transmission module communication check', estimatedRepairCost:'$150 – $1,500' },
  U0121: { code:'U0121', category:'Network', system:'CAN Bus', severity:'High', description:'Lost Communication with ABS Control Module', customerDescription:'ABS module is not communicating — ABS and traction control are disabled.', causes:['ABS module failure','CAN bus wiring fault','Blown fuse'], steps:['Check ABS module fuse','Inspect CAN wiring','Test module power/ground'], recommendation:'ABS module communication check', estimatedRepairCost:'$200 – $1,200' },
  U0155: { code:'U0155', category:'Network', system:'CAN Bus', severity:'Medium', description:'Lost Communication with Instrument Panel', customerDescription:'The instrument cluster is not receiving data — gauges may be incorrect or off.', causes:['Cluster wiring fault','Module failure','CAN bus issue'], steps:['Check cluster power/ground','Inspect CAN wiring to cluster'], recommendation:'Instrument cluster inspection', estimatedRepairCost:'$150 – $800' },
};

export function lookupDtc(code: string): DtcResult | null {
  const clean = code.trim().toUpperCase();
  return DTC_DATABASE[clean] ?? null;
}

export function searchDtc(query: string): DtcResult[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];
  return Object.values(DTC_DATABASE).filter(d =>
    d.code.includes(q) ||
    d.description.toUpperCase().includes(q) ||
    d.system.toUpperCase().includes(q) ||
    d.category.toUpperCase().includes(q)
  );
}

export const DTC_SYSTEMS = ['All', 'Ignition', 'O2 Sensor', 'Catalyst', 'Fuel System', 'EVAP', 'MAF', 'Throttle', 'Cooling', 'Oil', 'VVT', 'Timing', 'Transmission', 'Charging', 'Airbag', 'BCM', 'ABS/Brakes', 'Steering', 'CAN Bus', 'ECU'];
export const DTC_CATEGORIES = ['All', 'Powertrain', 'Body', 'Chassis', 'Network'];
export const DTC_SEVERITIES: DtcResult['severity'][] = ['Critical', 'High', 'Medium', 'Low', 'Info'];

// Legacy mock export for backward compatibility
export { lookupDtc as default };
