/**
 * lib/intelligence-bus/event-types.ts
 *
 * Strongly typed event contracts for the Redline Intelligence Bus.
 * Every event extends RibBaseEvent which provides the full causality envelope.
 * No `any` types anywhere in this file.
 */

// ---------------------------------------------------------------------------
// Envelope constants
// ---------------------------------------------------------------------------

export const MAX_EVENT_DEPTH = 10;
export const RIB_SCHEMA_VERSION = '1.0' as const;

// ---------------------------------------------------------------------------
// Base envelope — required on every RIB event
// ---------------------------------------------------------------------------

export interface RibBaseEvent {
  /** Globally unique event identifier (UUID v4), auto-generated by publisher */
  eventId: string;
  /** Discriminator — narrows to a concrete event type */
  eventType: RibEventType;
  /** Event schema version for forward-compatibility */
  schemaVersion: typeof RIB_SCHEMA_VERSION;

  // -- Causality --
  /** When the business event actually occurred (caller-provided, ISO-8601) */
  occurredAt: string;
  /** Groups all events in the same end-to-end workflow (trace ID) */
  correlationId: string;
  /** eventId that directly caused this event; null for root (user-initiated) events */
  causationId: string | null;
  /** 0 for root events; increments once per derived event in a causal chain */
  eventDepth: number;
  /** Module that published this event (e.g. 'vehicle_health', 'diagnostic_orchestrator') */
  originModule: string;

  // -- Tenant --
  /** Multi-tenant organization identifier */
  organizationId: string;
  /** Shop this event belongs to (UUID) */
  shopId: string;

  // -- Actor --
  /** Technician who triggered the action; null for system-generated events */
  technicianId: string | null;
  /** Vehicle involved in this event; null when not vehicle-specific */
  vehicleId: string | null;
  /** Diagnostic session context; null when not session-specific */
  diagnosticSessionId: string | null;
}

// ---------------------------------------------------------------------------
// Event type union — every known event type string literal
// ---------------------------------------------------------------------------

export type RibEventType =
  | 'vehicle.connected'
  | 'vehicle.identified'
  | 'vehicle.disconnected'
  | 'vehicle.mileage_updated'
  | 'diagnostic.session.created'
  | 'diagnostic.session.completed'
  | 'diagnostic.module.detected'
  | 'diagnostic.dtc.read'
  | 'diagnostic.freeze_frame.captured'
  | 'diagnostic.live_data.captured'
  | 'diagnostic.waveform.uploaded'
  | 'diagnostic.measurement.recorded'
  | 'diagnostic.image.uploaded'
  | 'diagnostic.pdf.uploaded'
  | 'diagnostic.reasoning.requested'
  | 'diagnostic.reasoning.completed'
  | 'diagnostic.claude_review.completed'
  | 'diagnostic.hypothesis.updated'
  | 'diagnostic.next_test.generated'
  | 'diagnostic.technician_result.entered'
  | 'repair.verified'
  | 'repair.recommendation.created'
  | 'service.completed'
  | 'job_card.updated'
  | 'estimate.approved'
  | 'invoice.paid'
  | 'customer.notified'
  | 'vehicle.health.updated'
  | 'fleet.health.updated'
  | 'inventory.recommendation.created'
  | 'failure.predicted';

/**
 * Event types whose side effects MUST be suppressed during replay.
 * These events trigger external communications or financial mutations.
 */
export const REPLAY_SUPPRESSED_EVENT_TYPES = new Set<RibEventType>([
  'customer.notified',
  'invoice.paid',
  'estimate.approved',
]);

// ---------------------------------------------------------------------------
// Payload reference type — use for large or binary data
// ---------------------------------------------------------------------------

/** Reference to an externally stored asset. Never embed binary data inline. */
export interface RibPayloadReference {
  storageProvider: 'supabase_storage' | 's3' | 'local';
  objectKey: string;
  contentType: string;
  sizeBytes: number;
  checksum: string;
  schemaVersion: string;
  accessClassification: 'shop_private' | 'tenant_private' | 'global_anonymized';
}

// ---------------------------------------------------------------------------
// Concrete event interfaces
// ---------------------------------------------------------------------------

export interface VehicleConnectedEvent extends RibBaseEvent {
  eventType: 'vehicle.connected';
  vin: string | null;
  hardwareType: string;
  bridgeDeviceId: string | null;
  protocolDetected: string | null;
}

export interface VehicleIdentifiedEvent extends RibBaseEvent {
  eventType: 'vehicle.identified';
  vin: string;
  year: number | null;
  make: string | null;
  model: string | null;
  engineCode: string | null;
  ecuCount: number;
}

export interface VehicleDisconnectedEvent extends RibBaseEvent {
  eventType: 'vehicle.disconnected';
  durationSeconds: number;
}

export interface VehicleMileageUpdatedEvent extends RibBaseEvent {
  eventType: 'vehicle.mileage_updated';
  previousOdometerKm: number | null;
  currentOdometerKm: number;
  source: 'manual' | 'obd' | 'bridge';
}

export interface DiagnosticSessionCreatedEvent extends RibBaseEvent {
  eventType: 'diagnostic.session.created';
  vehicleYear: number | null;
  vehicleMake: string | null;
  vehicleModel: string | null;
  complaintText: string | null;
}

export interface DiagnosticSessionCompletedEvent extends RibBaseEvent {
  eventType: 'diagnostic.session.completed';
  finalStatus: string;
  dtcCodesFound: string[];
  hypothesisCount: number;
  confirmedRepair: boolean;
  totalDurationMinutes: number;
}

export interface DiagnosticModuleDetectedEvent extends RibBaseEvent {
  eventType: 'diagnostic.module.detected';
  moduleId: string;
  moduleName: string;
  address: string;
  protocol: string;
  dtcCount: number;
}

export interface DiagnosticDtcReadEvent extends RibBaseEvent {
  eventType: 'diagnostic.dtc.read';
  dtcCode: string;
  description: string | null;
  system: string | null;
  moduleId: string | null;
  isPending: boolean;
  isPermanent: boolean;
  odometerKm: number | null;
}

export interface DiagnosticFreezeFrameCapturedEvent extends RibBaseEvent {
  eventType: 'diagnostic.freeze_frame.captured';
  dtcCode: string;
  parameters: Record<string, { value: number; unit: string }>;
  capturedAt: string;
}

export interface DiagnosticLiveDataCapturedEvent extends RibBaseEvent {
  eventType: 'diagnostic.live_data.captured';
  durationSeconds: number;
  sampleCount: number;
  pidCodes: string[];
  captureId: string;
  /** Reference to the full capture in storage — never embed sample data inline */
  storageRef: RibPayloadReference | null;
}

export interface DiagnosticWaveformUploadedEvent extends RibBaseEvent {
  eventType: 'diagnostic.waveform.uploaded';
  channel: string;
  durationMs: number;
  sampleRate: number;
  /** Reference to waveform in storage — never embed raw waveform data inline */
  storageRef: RibPayloadReference;
}

export interface DiagnosticMeasurementRecordedEvent extends RibBaseEvent {
  eventType: 'diagnostic.measurement.recorded';
  measurementType: string;
  value: number;
  unit: string;
  sourceModule: string;
  passOrFail: 'pass' | 'fail' | 'inconclusive' | null;
}

export interface DiagnosticImageUploadedEvent extends RibBaseEvent {
  eventType: 'diagnostic.image.uploaded';
  fileName: string;
  mimeType: string;
  capturedAt: string | null;
  /** Reference to image in storage — never embed base64 inline */
  storageRef: RibPayloadReference;
}

export interface DiagnosticPdfUploadedEvent extends RibBaseEvent {
  eventType: 'diagnostic.pdf.uploaded';
  fileName: string;
  documentType: 'tsb' | 'wiring_diagram' | 'service_manual' | 'estimate' | 'other';
  /** Reference to PDF in storage — never embed binary inline */
  storageRef: RibPayloadReference;
}

export interface DiagnosticReasoningRequestedEvent extends RibBaseEvent {
  eventType: 'diagnostic.reasoning.requested';
  providerName: string;
  modelName: string;
  promptVersion: string;
  dtcCodes: string[];
  hypothesisCount: number;
}

export interface DiagnosticReasoningCompletedEvent extends RibBaseEvent {
  eventType: 'diagnostic.reasoning.completed';
  providerName: string;
  modelName: string;
  hypothesesGenerated: number;
  primaryHypothesis: string | null;
  confidenceScore: number;
  durationMs: number;
  isSimulated: boolean;
}

export interface DiagnosticClaudeReviewCompletedEvent extends RibBaseEvent {
  eventType: 'diagnostic.claude_review.completed';
  reviewedHypotheses: number;
  agreementLevel: 'agree' | 'partial' | 'disagree';
  additionalInsights: boolean;
  confidenceAdjustment: number;
  durationMs: number;
}

export interface DiagnosticHypothesisUpdatedEvent extends RibBaseEvent {
  eventType: 'diagnostic.hypothesis.updated';
  hypothesisId: string;
  description: string;
  confidenceScore: number;
  confidenceBand: string;
  action: 'created' | 'updated' | 'promoted' | 'dismissed';
  isAiDerived: boolean;
}

export interface DiagnosticNextTestGeneratedEvent extends RibBaseEvent {
  eventType: 'diagnostic.next_test.generated';
  testPlanId: string;
  testCount: number;
  primaryTestDescription: string;
  estimatedMinutes: number;
}

export interface DiagnosticTechnicianResultEnteredEvent extends RibBaseEvent {
  eventType: 'diagnostic.technician_result.entered';
  testResultId: string;
  testDescription: string;
  outcome: 'pass' | 'fail' | 'inconclusive';
  value: string | null;
  unit: string | null;
  notes: string | null;
}

export interface RepairVerifiedEvent extends RibBaseEvent {
  eventType: 'repair.verified';
  repairCaseId: string;
  dtcCodesFixed: string[];
  rootCause: string;
  partsReplaced: string[];
  laborMinutes: number;
  outcomeStatus: 'resolved' | 'partial' | 'comeback';
  technicianNotes: string | null;
  totalCost: number | null;
  customerId: string | null;
}

export interface RepairRecommendationCreatedEvent extends RibBaseEvent {
  eventType: 'repair.recommendation.created';
  recommendationId: string;
  description: string;
  estimatedCost: number | null;
  urgency: 'critical' | 'high' | 'medium' | 'low';
  basedOnHypothesis: string | null;
}

export interface ServiceCompletedEvent extends RibBaseEvent {
  eventType: 'service.completed';
  serviceType: string;
  laborMinutes: number;
  partsUsed: string[];
  nextServiceDueKm: number | null;
  nextServiceDueDate: string | null;
}

export interface JobCardUpdatedEvent extends RibBaseEvent {
  eventType: 'job_card.updated';
  jobCardId: string;
  previousStatus: string;
  newStatus: string;
  customerId: string | null;
  estimatedCompletionAt: string | null;
}

export interface EstimateApprovedEvent extends RibBaseEvent {
  eventType: 'estimate.approved';
  estimateId: string;
  approvedAmount: number;
  currency: string;
  customerId: string | null;
  lineItemCount: number;
}

export interface InvoicePaidEvent extends RibBaseEvent {
  eventType: 'invoice.paid';
  invoiceId: string;
  amount: number;
  currency: string;
  customerId: string | null;
  paymentMethod: string;
}

export interface CustomerNotifiedEvent extends RibBaseEvent {
  eventType: 'customer.notified';
  customerId: string;
  channel: 'sms' | 'email' | 'line' | 'whatsapp' | 'push' | 'in_app';
  notificationType: string;
  success: boolean;
}

export interface VehicleHealthUpdatedEvent extends RibBaseEvent {
  eventType: 'vehicle.health.updated';
  overallScore: number;
  previousScore: number | null;
  systemScores: Record<string, number>;
  criticalSystemsAffected: string[];
}

export interface FleetHealthUpdatedEvent extends RibBaseEvent {
  eventType: 'fleet.health.updated';
  customerId: string;
  fleetSize: number;
  fleetHealthScore: number;
  highMaintenanceCount: number;
  recurringPatternCount: number;
}

export interface InventoryRecommendationCreatedEvent extends RibBaseEvent {
  eventType: 'inventory.recommendation.created';
  partNumber: string | null;
  partName: string;
  currentStock: number;
  recommendedReorderQty: number;
  urgency: 'critical' | 'high' | 'medium' | 'low';
  estimatedDaysUntilStockout: number | null;
}

export interface FailurePredictedEvent extends RibBaseEvent {
  eventType: 'failure.predicted';
  predictionId: string;
  componentName: string;
  failureProbability: number;
  estimatedMileageAtFailure: number | null;
  estimatedDaysUntilFailure: number | null;
  evidenceType: string;
  isAiDerived: false;
}

// ---------------------------------------------------------------------------
// Discriminated union
// ---------------------------------------------------------------------------

export type RibEvent =
  | VehicleConnectedEvent
  | VehicleIdentifiedEvent
  | VehicleDisconnectedEvent
  | VehicleMileageUpdatedEvent
  | DiagnosticSessionCreatedEvent
  | DiagnosticSessionCompletedEvent
  | DiagnosticModuleDetectedEvent
  | DiagnosticDtcReadEvent
  | DiagnosticFreezeFrameCapturedEvent
  | DiagnosticLiveDataCapturedEvent
  | DiagnosticWaveformUploadedEvent
  | DiagnosticMeasurementRecordedEvent
  | DiagnosticImageUploadedEvent
  | DiagnosticPdfUploadedEvent
  | DiagnosticReasoningRequestedEvent
  | DiagnosticReasoningCompletedEvent
  | DiagnosticClaudeReviewCompletedEvent
  | DiagnosticHypothesisUpdatedEvent
  | DiagnosticNextTestGeneratedEvent
  | DiagnosticTechnicianResultEnteredEvent
  | RepairVerifiedEvent
  | RepairRecommendationCreatedEvent
  | ServiceCompletedEvent
  | JobCardUpdatedEvent
  | EstimateApprovedEvent
  | InvoicePaidEvent
  | CustomerNotifiedEvent
  | VehicleHealthUpdatedEvent
  | FleetHealthUpdatedEvent
  | InventoryRecommendationCreatedEvent
  | FailurePredictedEvent;

export type RibEventOfType<T extends RibEventType> = Extract<RibEvent, { eventType: T }>;
