/**
 * Automotive Triage Engine — Question Rules
 * Maps complaint categories to question IDs and inspection suggestions.
 * All rule logic lives here — never in the UI.
 */

import { CategoryId } from './QuestionTypes';

// ─── Inspection suggestions per category ──────────────────────────────────────

export const INSPECTION_SUGGESTIONS: Record<CategoryId, string[]> = {
  engine: [
    'Scan for DTCs and record all codes',
    'Check engine oil level and condition',
    'Inspect air filter and intake system',
    'Check for vacuum leaks (smoke test)',
    'Inspect fuel pressure',
    'Check ignition system (plugs, coils)',
    'Compression and/or leakdown test',
    'Inspect exhaust for excessive smoke',
  ],
  transmission: [
    'Check transmission fluid level and condition',
    'Scan for transmission DTCs',
    'Road test — note shift points and feel',
    'Inspect for external fluid leaks',
    'Check transmission mount',
    'Review fluid service history',
  ],
  electrical: [
    'Scan all modules for DTCs',
    'Perform battery and charging system test',
    'Inspect fuse boxes (main + cabin)',
    'Check grounds and main power feeds',
    'Oscilloscope on suspect circuits',
    'Inspect recent work / aftermarket accessories',
  ],
  starting: [
    'Battery load test',
    'Starter current draw test',
    'Check for immobilizer / security codes',
    'Fuel pressure test (key on)',
    'Inspect ignition switch and relay',
    'Scan for communication bus faults (U codes)',
  ],
  battery: [
    'Battery load test (CCA vs rating)',
    'Charging voltage at idle and 2000 RPM',
    'Parasitic drain test (< 50 mA threshold)',
    'Inspect battery terminals and cables',
    'Check battery date code',
  ],
  charging: [
    'Charging voltage test at idle and 2000 RPM',
    'Alternator output current test',
    'Serpentine belt inspection',
    'Inspect alternator wiring harness',
    'Battery load test (rule out battery as cause)',
  ],
  cooling: [
    'Check coolant level and condition',
    'Pressure test cooling system',
    'Inspect hoses, clamps, and radiator',
    'Test thermostat operation',
    'Inspect water pump for weep hole seepage',
    'Check cooling fan operation (low and high speed)',
    'Block test for combustion gases in coolant',
  ],
  ac: [
    'High side and low side pressure readings',
    'Inspect condenser for blockage',
    'Compressor clutch engagement test',
    'Cooling fan operation check (low and high speed)',
    'Refrigerant charge level (manifold gauge set)',
    'Inspect for refrigerant leaks (UV dye / sniffer)',
    'Cabin air filter inspection',
    'Blend door actuator operation',
  ],
  heating: [
    'Coolant level and temperature check',
    'Heater core flow test',
    'Blower motor current draw',
    'Blend door actuator operation',
    'Heater control valve (if applicable)',
    'Inspect for air pockets in cooling system',
  ],
  brake: [
    'Brake pad thickness (front and rear)',
    'Rotor thickness and run-out measurement',
    'Brake fluid condition and moisture content',
    'Caliper slide pin operation',
    'Brake hose inspection (swollen / restricted)',
    'ABS module scan if light on',
    'Parking brake operation',
  ],
  steering: [
    'Power steering fluid level and condition',
    'Inspect for power steering leaks',
    'Tie rod end and ball joint inspection',
    'Steering rack / gearbox for play',
    'EPAS scan if electric system',
    'Wheel alignment angles',
    'Tyre condition and pressure',
  ],
  suspension: [
    'Shock absorber / strut bounce test',
    'Ball joint inspection (lift test)',
    'Control arm bushing inspection',
    'Sway bar link and bushing inspection',
    'Wheel bearing play check',
    'Tyre condition and wear pattern',
    'Alignment angles',
  ],
  noise: [
    'Road test — reproduce noise (note speed, conditions)',
    'Inspect wheel bearings (noise with speed)',
    'Inspect brakes (noise on braking)',
    'Check heat shields and exhaust hangers',
    'Inspect drive shaft / CV axle joints',
    'Lift and inspect for loose exhaust components',
  ],
  vibration: [
    'Tyre balance (road force recommended)',
    'Tyre condition (cupping / flat spots)',
    'Drive shaft / prop shaft balance',
    'Wheel hub run-out check',
    'Engine and transmission mount inspection',
    'CV axle inspection',
  ],
  oil_leak: [
    'Clean and degrease leak area',
    'UV dye trace to identify source',
    'Inspect valve cover gaskets',
    'Inspect oil pan gasket',
    'Inspect front and rear main seals',
    'Check oil filter and drain plug',
    'Inspect cam / crank sensor O-rings',
  ],
  fuel: [
    'Fuel pressure test (key on and running)',
    'Inspect fuel lines and connections',
    'Injector balance test',
    'Check fuel trim data (short and long term)',
    'Evap system smoke test',
    'Inspect fuel cap and filler neck',
  ],
  programming: [
    'Confirm correct module / part number',
    'Check for TSB / software update',
    'Verify battery voltage is adequate before programming',
    'Obtain security access if required',
    'Perform module configuration / variant coding after flash',
    'Complete system re-learn procedure',
  ],
  immobilizer: [
    'Scan for immobilizer DTCs (B codes)',
    'Check key transponder with reader',
    'Inspect ignition switch wiring',
    'Check BCM / ECM communication',
    'Verify correct key / fob ID in system',
  ],
  adas: [
    'Scan all ADAS modules for DTCs',
    'Check camera and sensor mounting / alignment',
    'Confirm windscreen replacement specifications met',
    'Perform static and dynamic calibration',
    'Road test to verify system operation',
    'Check for software update (TSB)',
  ],
  hybrid: [
    'Scan HV system for DTCs',
    'Auxiliary 12V battery test',
    'HV battery capacity and cell balance check',
    'Inspect HV cable harness and connectors',
    'Inspect coolant for HV battery thermal system',
    'Hybrid inverter inspection',
  ],
  ev: [
    'Scan BMS for DTCs and cell data',
    'Inspect charging port and cable',
    'Verify charge network / EVSE function',
    'Thermal management system check',
    'HV battery state of health report',
    'Inspect HV connectors and service plug',
    'Check 12V auxiliary battery',
  ],
  other: [
    'Perform a thorough visual inspection',
    'Scan all modules for DTCs',
    'Road test to reproduce complaint',
    'Document all findings with photos',
  ],
};

// ─── Question ordering per category (which questions are "priority") ──────────

export const PRIORITY_QUESTION_IDS: Record<CategoryId, string[]> = {
  engine:       ['eng_symptom', 'eng_warning_lights', 'eng_dtc_scanned'],
  transmission: ['trans_symptom', 'trans_type', 'trans_warning_lights'],
  electrical:   ['elec_symptom', 'elec_warning_lights', 'elec_battery_tested'],
  starting:     ['start_symptom', 'start_booster', 'start_immobilizer_light'],
  battery:      ['bat_symptom', 'bat_age', 'bat_tested'],
  charging:     ['chg_warning_light', 'chg_symptom', 'chg_voltage_checked'],
  cooling:      ['cool_symptom', 'cool_warning_light', 'cool_coolant_level_ok'],
  ac:           ['ac_cold_idle', 'ac_cold_driving', 'ac_compressor_engaging'],
  heating:      ['heat_symptom', 'heat_blower', 'heat_coolant_level'],
  brake:        ['brk_noise', 'brk_soft_pedal', 'brk_abs_light'],
  steering:     ['str_symptom', 'str_warning_light', 'str_fluid_ok'],
  suspension:   ['sus_symptom', 'sus_location', 'sus_noise'],
  noise:        ['noise_type', 'noise_origin', 'noise_when'],
  vibration:    ['vib_location', 'vib_when', 'vib_speed'],
  oil_leak:     ['oil_severity', 'oil_location', 'oil_type'],
  fuel:         ['fuel_symptom', 'fuel_smell_location', 'fuel_warning_light'],
  programming:  ['prog_type', 'prog_module_replaced', 'prog_tool_required'],
  immobilizer:  ['immo_symptom', 'immo_light_on', 'immo_key_programme'],
  adas:         ['adas_system', 'adas_warning_light', 'adas_calibration_needed'],
  hybrid:       ['hyb_symptom', 'hyb_warning_light', 'hyb_battery_health'],
  ev:           ['ev_symptom', 'ev_charge_level', 'ev_warning_light'],
  other:        ['other_category', 'other_description', 'other_warning_light'],
};
